name: SpectatorBorderGuard
version: 1.0.1
main: com.hamta.spectatorborderguard.SpectatorBorderGuard
api-version: '1.20'
description: Prevents players in spectator mode from leaving the world border.
author: HamtaBot
